//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace To_Do__MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_item
    {
        public int todo_id { get; set; }
        public string todo_title { get; set; }
        public string todo_description { get; set; }
        public bool todo_completed { get; set; }
        public System.DateTime todo_dateadded { get; set; }
    }

    public class ItemModel { 
        public List<todo_item> ToDoItemList { get; set; }

    }

}
